# Generated by Django 3.0.2 on 2020-01-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_mentor',
            field=models.BooleanField(default=False),
        ),
    ]
