# Generated by Django 3.0.2 on 2020-01-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=255)),
                ('held_date', models.DateField()),
                ('start_timings', models.TimeField()),
                ('end_timings', models.TimeField()),
            ],
        ),
    ]
