# Generated by Django 3.0.2 on 2020-01-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Developers Conference', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='genre',
            field=models.CharField(default='Company Development', max_length=255),
        ),
    ]
