# Generated by Django 3.0.2 on 2020-01-18 09:01

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default=company.models.generate_id, max_length=25, unique=True),
        ),
    ]
